import Foundation

struct ScanTechnicalReport: Codable {
    var createdAt: String
    var markerProfile: String
    var stlFileName: String?
    var diagnosticsFileName: String?
    var deviceModelIdentifier: String?
    var deviceMarketingName: String?
    var cameraProfileId: String?
    var cameraProfileName: String?
    var cameraRecommendedProfileId: String?
    var cameraRecommendedProfileName: String?
    var cameraProfileTooCloseFocusRiskDistanceMm: Double?
    var cameraProfilePreferredMinScanDistanceMm: Double?
    var cameraProfilePreferredIdealMinScanDistanceMm: Double?
    var cameraProfilePreferredIdealMaxScanDistanceMm: Double?
    var cameraProfilePreferredMaxScanDistanceMm: Double?
    var deviceQualityClass: String?
    var deviceQualityProfileName: String?
    var deviceQualityIsKnown: Bool?
    var deviceQualityWarning: String?
    var deviceQualityMinDistanceMm: Double?
    var deviceQualityIdealMinDistanceMm: Double?
    var deviceQualityIdealMaxDistanceMm: Double?
    var deviceQualityMaxDistanceMm: Double?
    var deviceQualityTooCloseFocusRiskDistanceMm: Double?
    var deviceQualityFocusVarianceThreshold: Double?
    var deviceQualityOverlayScale: Double?
    var deviceQualityFrameMaskVerticalBorderPercent: Double?
    var deviceQualityFrameMaskHorizontalBorderPercent: Double?
    var selectedCameraLocalizedName: String?
    var selectedCameraDeviceType: String?
    var requestedZoomFactor: Double?
    var appliedZoomFactor: Double?
    var currentVideoZoomFactor: Double?
    var focusMode: String?
    var exposureMode: String?
    var isAdjustingFocus: Bool?
    var isAdjustingExposure: Bool?
    var cameraIntrinsicMatrixAvailable: Bool?
    var cameraIntrinsicFx: Double?
    var cameraIntrinsicFy: Double?
    var cameraIntrinsicCx: Double?
    var cameraIntrinsicCy: Double?
    var activeVideoDimensions: String?
    var activeFormatDescription: String?
    var cameraProfileEvaluationScore: Double?
    var cameraProfileEvaluationWarnings: [String]?
    var device: Device
    var cameraQuality: CameraQuality
    var markers: [Marker]
    var scanQuality: ScanQuality
    var expectedMarkerCount: Int?
    var exportedMarkerCount: Int?
    var missingMarkerIds: [Int]?
    var invalidMarkerIds: [Int]?
    var exportBlockedReason: String?
    var exportGateProfile: String?
    var markerExportValidations: [MarkerExportValidation]?
    var scanConfiguration: ScanConfiguration?
    var focusRecoveryState: String?
    var lastFocusTarget: String?
    var arucoLostCount: Int?
    var centerFocusRecoveryCount: Int?
    var distanceGuideState: String?
    var distanceGuideMessage: String?
    var lastDistanceMm: Double?
    var distanceGuideBarMinMm: Double?
    var distanceGuideBarMaxMm: Double?
    var distanceGuideIdealBandMinMm: Double?
    var distanceGuideIdealBandMaxMm: Double?
    var frameMaskSafeRectMinX: Double?
    var frameMaskSafeRectMinY: Double?
    var frameMaskSafeRectMaxX: Double?
    var frameMaskSafeRectMaxY: Double?
    var visibleMarkersInsideFrameMaskCount: Int?
    var visibleMarkersViolatingFrameMaskCount: Int?
    var anyMarkerNearFrameEdge: Bool?
    var frameMaskQualityState: String?
    var frameMaskQualityMessage: String?
    var experimentalQualityModeEnabled: Bool?
    var experimentalObservationGateEnabled: Bool?
    var experimentalMinValidFramesPerMarker: Int?
    var experimentalTargetOptimizationFrames: Int?
    var experimentalRawObservationCount: Int?
    var experimentalAcceptedObservationCount: Int?
    var experimentalRejectedObservationCount: Int?
    var experimentalRejectedByFrameMaskCount: Int?
    var experimentalRejectedByTooCloseCount: Int?
    var experimentalRejectedByTooFarCount: Int?
    var experimentalRejectedByFocusRiskCount: Int?
    var experimentalRejectedByInvalidPoseCount: Int?
    var experimentalRejectedByNotFiniteCount: Int?
    var experimentalRejectedByUnknownCount: Int?
    var experimentalUsefulMarkersReadyCount: Int?
    var experimentalUsefulAllMarkersReady: Bool?
    var experimentalOverallUsefulProgress: Double?
    var cameraHighResolutionProfileAvailable: Bool?
    var cameraHighResolutionProfileSelected: Bool?
    var cameraRequestedHighResolutionDimensions: String?
    var cameraAppliedHighResolutionDimensions: String?
    var cameraHighResolutionFallbackReason: String?
    var cameraAvailableFormatCount: Int?
    var cameraAvailableMaxResolutionWidth: Int?
    var cameraAvailableMaxResolutionHeight: Int?
    var referenceCameraMatrixDiagnosticsEnabled: Bool?
    var referenceCameraMatrixSource: String?
    var referenceCameraMatrixFx: Double?
    var referenceCameraMatrixFy: Double?
    var referenceCameraMatrixCx: Double?
    var referenceCameraMatrixCy: Double?
    var activeCameraIntrinsicFx: Double?
    var activeCameraIntrinsicFy: Double?
    var activeCameraIntrinsicCx: Double?
    var activeCameraIntrinsicCy: Double?
    var referenceVsActiveFxDelta: Double?
    var referenceVsActiveFyDelta: Double?
    var referenceVsActiveCxDelta: Double?
    var referenceVsActiveCyDelta: Double?
    var referenceVsActiveFxRatio: Double?
    var referenceVsActiveFyRatio: Double?
    var referenceCameraMatrixResolutionMismatchWarning: String?
    var roiCenterNormalizedX: Double?
    var roiCenterNormalizedY: Double?
    var lastFocusPointNormalizedX: Double?
    var lastFocusPointNormalizedY: Double?
    var lastExposurePointNormalizedX: Double?
    var lastExposurePointNormalizedY: Double?
    var focusPointInsideROI: Bool?
    var focusPointDistanceToROICenter: Double?
    var experimentalAngularSamplesCount: Int?
    var experimentalAngularUsefulSamplesCount: Int?
    var experimentalAngularStdDeg: Double?
    var experimentalAngularMinSeparationDeg: Double?
    var experimentalAngleDiversityScore: Double?
    var experimentalAngleDiversityReady: Bool?
    var tagAreaPixelsMean: Double?
    var userFeedbackState: String?
    var userFeedbackMessage: String?
    var captureProgressPercent: Double?
    var refinementProgressPercent: Double?
    var friendlyBlockingReason: String?
    var normalFinalizationState: String?
    var normalFinalizationStartedAtSeconds: Double?
    var normalFinalizationDurationSeconds: Double?
    var normalFinalizationFramesAccepted: Int?
    var normalFinalizationFramesRejectedByFocus: Int?
    var normalFinalizationFramesRejectedByMotion: Int?
    var normalFinalizationFramesRejectedByReprojection: Int?
    var normalFinalizationFramesRejectedByNormal: Int?
    var autoExportTriggered: Bool?
    var normalFinalizationMinFinalObservationsPerMarker: Int?
    var normalFinalizationTargetAverageObservationsPerMarker: Int?
    var normalFinalizationMinObservationsReached: Bool?
    var normalFinalizationAverageObservationsReached: Bool?
    var normalFinalizationAverageObservationsPerMarker: Double?
    var normalFinalizationMaxNormalStdDegrees: Double?
    var normalFinalizationNormalGatePassed: Bool?
    var normalFinalizationMaturityGatePassed: Bool?
    var normalFinalizationAutoExportReason: String?
    var normalFinalizationBlockedReason: String?
    var normalFinalizationMinObservationsByMarker: [Int: Int]?
    var allExpectedMarkersAt100Percent: Bool?
    var expectedMarkerProgressById: [Int: Double]?
    var usedBestFinalPoseCandidate: Bool?
    var bestFinalPoseCandidateSaved: Bool?
    var bestFinalPoseCandidateScore: Double?
    var bestFinalPoseCandidateTimestampSeconds: Double?
    var bestFinalPoseCandidateLastUpdatedAtSeconds: Double?
    var bestFinalPoseCandidateAgeSeconds: Double?
    var bestFinalPoseCandidateWorstNormalStd: Double?
    var bestFinalPoseCandidateWorstReprojection: Double?
    var bestFinalPoseCandidateObservationsByMarker: [Int: Int]?
    var bestFinalPoseCandidateReason: String?
    var bestFinalPoseCandidateMarkerIds: [Int]?
    var bestFinalPoseCandidateHasExportablePoses: Bool?
    var bestFinalPoseCandidateAcceptedCount: Int?
    var bestFinalPoseCandidateLastRejectReason: String?
    var bestFinalPoseCandidateGeometryAdjustedScore: Double?
    var bestFinalPoseCandidateGeometryPenalty: Double?
    var bestFinalPoseCandidateGeometryScoreSource: String?
    var relativeMarkerDistanceM01: Double?
    var relativeMarkerDistanceM02: Double?
    var relativeMarkerDistanceM03: Double?
    var relativeMarkerDistanceM12: Double?
    var relativeMarkerDistanceM13: Double?
    var relativeMarkerDistanceM23: Double?
    var relativeMarkerDistanceStdMean: Double?
    var relativeMarkerDistanceStdMax: Double?
    var relativeMarkerGeometryScore: Double?
    var candidateVsFinalTranslationDeltaMean: Double?
    var candidateVsFinalRotationDeltaMean: Double?
    var candidateVsFinalGeometryDelta: Double?
    var guidedStaticCaptureEnabled: Bool?
    var guidedStaticStages: [GuidedStaticStage]?

    struct Device: Codable {
        var model: String?
        var iosVersion: String?
        var cameraDevice: String?
        var resolution: String?
        var zoomFactor: Double?
    }

    struct CameraQuality: Codable {
        var focusLocked: Bool?
        var sharpnessMean: Double?
        var framesRejectedByFocus: Int
        var framesRejectedByBlur: Int
    }

    struct Marker: Codable {
        var markerId: Int
        var translationVector: [Double]?
        var rotationMatrix: [[Double]]?
        var confidence: String?
        var qualityScore: Double?
        var dualFrames: Int?
        var topFallbackFrames: Int?
        var bottomFallbackFrames: Int?
        var reprojectionError: Double?
        var sharpnessMean: Double?
        var normalStdDegrees: Double?
        var finalObservationsUsed: Int?
        var markerFrameCenterX: Double?
        var markerFrameCenterY: Double?
        var markerFrameNormalizedCenterX: Double?
        var markerFrameNormalizedCenterY: Double?
        var markerFrameMinX: Double?
        var markerFrameMinY: Double?
        var markerFrameMaxX: Double?
        var markerFrameMaxY: Double?
        var markerInsideFrameMask: Bool?
        var markerFrameMaskViolation: String?
        var markerDistanceToFrameMaskEdgePx: Double?
        var markerDistanceToFrameMaskEdgeNormalized: Double?
        var markerNearFrameEdgeWarning: Bool?
        var markerExperimentalRawObservationCount: Int?
        var markerExperimentalAcceptedObservationCount: Int?
        var markerExperimentalRejectedObservationCount: Int?
        var markerExperimentalRejectedByFrameMaskCount: Int?
        var markerExperimentalRejectedByTooCloseCount: Int?
        var markerExperimentalRejectedByTooFarCount: Int?
        var markerExperimentalRejectedByFocusRiskCount: Int?
        var markerExperimentalRejectedByInvalidPoseCount: Int?
        var markerExperimentalRejectedByNotFiniteCount: Int?
        var markerExperimentalRejectedByUnknownCount: Int?
        var markerExperimentalUsefulProgress: Double?
        var markerExperimentalUsefulReady: Bool?
    }

    struct ScanQuality: Codable {
        var confidence: String?
        var worstMarkerId: Int?
        var mainIssue: String?
        var planeAverageErrorMm: Double?
        var planeMaxErrorMm: Double?
    }

    struct MarkerExportValidation: Codable {
        var markerId: Int
        var exportGateProfile: String?
        var isExportable: Bool
        var reason: String?
        var isVisuallyRecent: Bool?
        var hasCurrentPose: Bool?
        var accumulatedObservationCount: Int?
        var finalObservationsUsed: Int?
    }

    struct ScanConfiguration: Codable {
        var markerProfile: String?
        var minimumCoveragePercentPerTag: Double?
        var minimumGoodFrames: Int?
        var targetGoodFrames: Int?
        var minimumDualTagFramesPerMarker: Int?
        var minimumDualAngularCoveragePercentPerMarker: Double?
        var precisionModeV2: Bool?
        var preferDualTagForFinalExport: Bool?
        var showDistanceGuide: Bool?
        var staticPoseStabilityMode: Bool?
        var arkitAssistedCaptureEnabled: Bool?
        var cameraZoomFactor: Double?
        var manualFocusEnabled: Bool?
        var manualLensPosition: Double?
        var lockFocusAndExposureForScan: Bool?
        var autoFocusOnDetectedAruco: Bool?
        var lockAfterArucoFocus: Bool?
        var guidedStaticCaptureEnabled: Bool?
        var guidedStaticRequiredStages: Int?
        var guidedStaticFramesPerStage: Int?
        var guidedStaticMinStableTimeSeconds: Double?
        var guidedStaticMaxNormalStdDegreesPerStage: Double?
        var guidedStaticRequireAllMarkersPerStage: Bool?
        var minimumAllowedSharpness: Double?
        var minimumPreferredSharpness: Double?
        var lensPositionChangeThreshold: Double?
        var focusSettleTimeSeconds: Double?
        var cameraProfileId: String?
        var cameraProfileName: String?
    }

    struct GuidedStaticStage: Codable {
        var stageName: String
        var framesAccepted: Int
        var framesRejectedByFocus: Int
        var framesRejectedByMotion: Int
        var framesRejectedByNormal: Int
        var framesRejectedByReprojection: Int
        var markersSeen: [Int]?
        var markersAccepted: [Int]?
        var normalStdDegreesMean: Double?
    }
}
